To rectify AttributeError
'pandas.core.algorithms' has no attribute 'quantile can be fixed by ysing quantile method from numpy

We won't be required to downgrade the pandas version.
Please review and approve.